# Generated by Django 3.2.25 on 2024-09-17 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtitle',
            options={'ordering': ['language'], 'verbose_name': 'Subtitle', 'verbose_name_plural': 'Subtitles'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='videos.video'),
        ),
        migrations.AlterModelTable(
            name='subtitle',
            table='videos_subtitle',
        ),
        migrations.AlterModelTable(
            name='video',
            table='videos_video',
        ),
    ]
