# Generated by Django 3.2.25 on 2024-09-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20240917_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='timestamp',
            field=models.DurationField(default='1'),
            preserve_default=False,
        ),
    ]
